package com.project.task.manager.ui.theme

import androidx.compose.ui.graphics.Color

val taskLightPrimary = Color(0xFF825500)
val taskLightOnPrimary = Color(0xFFFFFFFF)
val taskLightPrimaryContainer = Color(0xFFFFDDAE)
val taskLightOnPrimaryContainer = Color(0xFF2A1800)
val taskLightSecondary = Color(0xFF6F5B40)
val taskLightOnSecondary = Color(0xFFFFFFFF)
val taskLightSecondaryContainer = Color(0xFFFADEBC)
val taskLightOnSecondaryContainer = Color(0xFF271904)
val taskLightTertiary = Color(0xFF516440)
val taskLightOnTertiary = Color(0xFFFFFFFF)
val taskLightTertiaryContainer = Color(0xFFD3EABC)
val taskLightOnTertiaryContainer = Color(0xFF102004)
val taskLightError = Color(0xFFBA1B1B)
val taskLightErrorContainer = Color(0xFFFFDAD4)
val taskLightOnError = Color(0xFFFFFFFF)
val taskLightOnErrorContainer = Color(0xFF410001)
val taskLightBackground = Color(0xFFFCFCFC)
val taskLightOnBackground = Color(0xFF1F1B16)
val taskLightSurface = Color(0xFFFCFCFC)
val taskLightOnSurface = Color(0xFF1F1B16)
val taskLightSurfaceVariant = Color(0xFFF0E0CF)
val taskLightOnSurfaceVariant = Color(0xFF4F4539)
val taskLightOutline = Color(0xFF817567)
val taskLightInverseOnSurface = Color(0xFFF9EFE6)
val taskLightInverseSurface = Color(0xFF34302A)
val taskLightPrimaryInverse = Color(0xFFFFB945)

val taskDarkPrimary = Color(0xFFFFB945)
val taskDarkOnPrimary = Color(0xFF452B00)
val taskDarkPrimaryContainer = Color(0xFF624000)
val taskDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val taskDarkSecondary = Color(0xFFDDC3A2)
val taskDarkOnSecondary = Color(0xFF3E2E16)
val taskDarkSecondaryContainer = Color(0xFF56442B)
val taskDarkOnSecondaryContainer = Color(0xFFFADEBC)
val taskDarkTertiary = Color(0xFFB8CEA2)
val taskDarkOnTertiary = Color(0xFF243516)
val taskDarkTertiaryContainer = Color(0xFF3A4C2B)
val taskDarkOnTertiaryContainer = Color(0xFFD3EABC)
val taskDarkError = Color(0xFFFFB4A9)
val taskDarkErrorContainer = Color(0xFF930006)
val taskDarkOnError = Color(0xFF680003)
val taskDarkOnErrorContainer = Color(0xFFFFDAD4)
val taskDarkBackground = Color(0xFF1F1B16)
val taskDarkOnBackground = Color(0xFFEAE1D9)
val taskDarkSurface = Color(0xFF1F1B16)
val taskDarkOnSurface = Color(0xFFEAE1D9)
val taskDarkSurfaceVariant = Color(0xFF4F4539)
val taskDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val taskDarkOutline = Color(0xFF9C8F80)
val taskDarkInverseOnSurface = Color(0xFF32281A)
val taskDarkInverseSurface = Color(0xFFEAE1D9)
val taskDarkPrimaryInverse = Color(0xFF624000)
